### ISSUE TITLE
Missing guestfish (must be installed manually)

### ISSUE THREAD

**Issue by micharbet** [OndrejHome/fast-vm#39]
On CentOS host with fresh installation of Fast-VM I obtained error message [1]
missing 'guestfish' was later installed manually and error while configuring netxt VM disappeared.
However the first one (#75 in my example) remained on storage and unconfigured - no host name, no network, etc..

Note: fast-vm was installed from rpm, so I think guestfish might be in dependencies

[1] 
$ fast-vm create centos-7.5 75
[75][inf] using file /etc/fast-vm/config-centos-7.5.xml as libvirt XML
[75][inf] using file /etc/fast-vm/hacks-centos-7.5.sh as hack file
[75][inf] defining virtual machine 'fastvm-centos-7.5-75' in libvirt
Domain fastvm-centos-7.5-75 defined from /tmp/tmp.6HhdGA53jp.xml

Domain title updated successfully
[75][inf] creating disk 'fastvm-centos-7.5-75'
[75][inf] adding static lease for 192.168.22.75 into libvirts DHCP
[75][inf] applying hacks from /etc/fast-vm/hacks-centos-7.5.sh
which: no guestfish in (/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin)
[!!!] Command 'guestfish' not found (Install it!). Making changes to VM FAILED.
[75][err] It is not possible to use image centos-7.5 for creating VM now as it is being used by fast-vm or other process at the moment

**Comment by OndrejHome** [comment]
HI @micharbet, this is expected as the guestfish is not a dependency of `fast-vm`, but rather a dependency of hack scripts that you have used. Despite this being mentioned in several places like:
- https://www.famera.cz/blog/fast-vm/user_guide.html#installation_from_package
- https://github.com/OndrejHome/fast-vm-public-images/blob/master/README#L19
I think I will be going out with next version to make this a dependency of some kind.
Will keep you updated on progress. Thank you for feedback.

**Comment by micharbet** [comment]
Excuse me sir for being ignorant and not reading thoroughly the documentation. I just... I just thought... nevermind. I'm happy you understand this semi-issue and you're willing to do the best for users of the great and unique Fast-VM :-)

**Comment by OndrejHome** [comment]
I also prefer not reading manual unless necessary. This issue is just confirmation that there is a gap that makes it not as easy as I thought and I think it would be good to close that gap. Thank you for reporting!

**Comment by OndrejHome** [comment]
Improved in commit 2b5d18c59e49a867f7314889580343ff172cab7f in `devel`. Will keep this open until it reaches the packaged version of fast-vm or `master` branch.
TODO:
- [x] update user_guide documentation and potentially other places

**Comment by OndrejHome** [comment]
New version 1.5 will now by default include also the guestfish on CentOS/RHEL/Fedora builds. There are not 2 packages - `fast-vm` and `fast-vm-minimal`. By default the `fast-vm` will pull in the needed dependencies. You can directly just update to newer version and it will pull in the dependencies.
Thank you again for feedback from this issue. Closing this now.
