### ISSUE TITLE
VM's names

### ISSUE THREAD

**Issue by micharbet** [OndrejHome/fast-vm#40]
Virtual machine gets following hostnames:
   `fastvm-DISTRO-V1-V2-VMNumber`
In my opinion it would be a little bit more practical if it was:
   `fastvm-VMNumber-DISTRO-V1-V2`

Not a big deal anyway :)

**Comment by OndrejHome** [comment]
Hi @micharbet ,
As we have discussed yesterday offline, the hostnames for VMs are changed by hack files from https://github.com/OndrejHome/fast-vm-public-images repository. Most (if not all) of them uses following as the formula for constructing the hostname. If you would like to just change the hostname of VM please have a look on below code and let me know if that would do the trick or if you would like to see also some other change.

https://github.com/OndrejHome/fast-vm-public-images/blob/e04c0b0d5486c768e97b7843d24c1fbae964c491/centos/hacks/6g_centos-7-hacks.sh#L11

**Comment by OndrejHome** [comment]
Hi @micharbet, please let me know if you have any further questions to this Issue.
If I don't hear from you within 2 weeks I will close it as I believe that this should be addressed in the 'fast-vm-public-images' repository as part of the 'hack files'. `fast-vm` itself only defines the VM names seen in the libvirt outputs (like `virsh list`). If the libvirt/virsh name is a concern please let me know.

**Comment by OndrejHome** [comment]
Closing this as mentioned in my previous comment. Feel free to re-open if that makes sense.
